
function svgData(title, colors){const cs=colors.map((c,i)=>`<circle cx="${85+i*100}" cy="${150+(i%2)*55}" r="68" fill="${c}" opacity=".9"/>`).join("");const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="620"><rect width="900" height="620" fill="#fff8ef"/><rect x="55" y="55" width="790" height="510" rx="52" fill="#f4eadf"/>${cs}<path d="M95 405 C210 280,330 475,460 350 S670 305,805 415" fill="none" stroke="#2e6b5f" stroke-width="22" stroke-linecap="round" opacity=".7"/><text x="78" y="525" font-family="Arial" font-size="52" font-weight="700" fill="#2b2723">${title}</text></svg>`;return "data:image/svg+xml;utf8,"+encodeURIComponent(svg);}
const rawLessons=[
{id:"jesenny-les",title:"Jesenný les",grade:"1. ročník",theme:"jeseň strom les listy",technique:"maľba",method:"Farba",duration:"90 minút",difficulty:"ľahká",goal:"Vnímať teplé farby a ich pôsobenie v obrazovej ploche.",tools:["temperové farby","štetce","papier A3","paleta"],procedure:["Rozhovor o farbách jesene.","Ukážka teplých farieb a miešanie.","Rozvrhnutie kompozície lesa.","Maľba farebných plôch.","Porovnanie nálady prác."],artists:[["Vincent van Gogh","Mulberry Tree, Autumn Landscape","expresívna farba a rukopis"],["Claude Monet","Poplars","farebná atmosféra krajiny"],["Gustav Klimt","Beech Forest I","dekoratívna plocha a rytmus"]],colors:["#d9822b","#b94e2f","#f0b43c","#6b3f1d"],standard:"Farba, vnímanie teplých farieb, výtvarné vyjadrovanie."},
{id:"zimna-krajina",title:"Zimná krajina",grade:"1. ročník",theme:"zima krajina sneh",technique:"maľba",method:"Farba",duration:"90 minút",difficulty:"ľahká",goal:"Vnímať studené farby a svetlé tóny v zimnej atmosfére.",tools:["temperové farby","biely papier","štetce","špongia"],procedure:["Rozhovor o farbách zimy.","Miešanie modrých a bielych tónov.","Maľba pozadia.","Doplnenie stromov alebo domov.","Porovnanie zimnej nálady."],artists:[["Claude Monet","The Magpie","svetlo a sneh"],["Pieter Bruegel starší","Hunters in the Snow","zimná krajina a priestor"]],colors:["#d9edf7","#7fb3d5","#eef7fb","#5d6d7e"],standard:"Farba, studené farby, nálada krajiny."},
{id:"farebne-akvarium",title:"Farebné akvárium",grade:"2. ročník",theme:"ryby voda akvárium fantázia",technique:"koláž",method:"Farba",duration:"90 minút",difficulty:"ľahká až stredná",goal:"Rozlišovať studené farby a vytvárať farebnú harmóniu v koláži.",tools:["farebné papiere","lepidlo","nožnice","modrý podklad"],procedure:["Rozhovor o podmorskom svete.","Výber studených farieb.","Tvorba podkladu.","Vystrihovanie rýb a rastlín.","Lepenie prvkov do celku."],artists:[["Henri Matisse","The Lagoon","koláž a farebná plocha"],["Paul Klee","Fish Magic","fantázia a symbolika"]],colors:["#1e88a8","#2fb7a3","#174b73","#a8e6e0"],standard:"Farba, studené farby, práca s materiálom, koláž."},
{id:"mesto-z-tvarov",title:"Mesto z tvarov",grade:"3. ročník",theme:"mesto architektúra domy geometria",technique:"kresba",method:"Kompozícia",duration:"90 minút",difficulty:"stredná",goal:"Umiestniť veľké a malé tvary na ploche a vytvoriť vyváženú kompozíciu.",tools:["papier A3","ceruzka","čierny fix","pastelky"],procedure:["Pozorovanie tvarov budov.","Rozvrhnutie dominanty.","Kresba mesta z geometrických tvarov.","Doplnenie rytmu okien.","Hodnotenie kompozície."],artists:[["Piet Mondrian","Broadway Boogie Woogie","rytmus a geometria"],["Paul Klee","Castle and Sun","stavba z tvarov"],["Ľudovít Fulla","Slovenská svadba","plošnosť a dekoratívnosť"]],colors:["#f2c94c","#eb5757","#2f80ed","#222"],standard:"Kompozícia, tvar, plocha, rytmus, dominanta."},
{id:"portret-emocia",title:"Portrét a emócia",grade:"4. ročník",theme:"portrét emócia výraz",technique:"kresba",method:"Výraz a štylizácia",duration:"90 minút",difficulty:"stredná",goal:"Vyjadriť emóciu pomocou línie, tvaru a výrazových prvkov tváre.",tools:["papier A3","ceruzka","uhlík","zrkadlo"],procedure:["Rozhovor o emóciách.","Pozorovanie proporcií tváre.","Kresba portrétu.","Zvýraznenie emócie.","Reflexia výrazu."],artists:[["Pablo Picasso","Weeping Woman","deformácia a emócia"],["Amedeo Modigliani","Portraits","štylizácia tváre"],["Edvard Munch","The Scream","expresívny pocit"]],colors:["#d85d5d","#2b2723","#e8c2a2","#8b5e4b"],standard:"Výraz, štylizácia, portrét, emócia."},
{id:"abstraktna-hudba",title:"Maľba podľa hudby",grade:"5. ročník",theme:"hudba abstrakcia rytmus",technique:"maľba",method:"Abstrakcia",duration:"90 minút",difficulty:"stredná až náročná",goal:"Previesť hudobný zážitok do farby, línie a rytmu obrazovej kompozície.",tools:["papier A3","tempery alebo akryl","štetce","hudobná ukážka"],procedure:["Počúvanie hudby.","Rozhovor o rytme a nálade.","Voľná maľba línií a plôch.","Doplnenie kontrastov.","Reflexia hudby v obraze."],artists:[["Wassily Kandinsky","Composition VIII","hudba, farba, abstrakcia"],["Paul Klee","Polyphony","rytmus obrazu"],["František Kupka","Amorpha","abstrakcia a pohyb"]],colors:["#3d5afe","#fdd835","#e53935","#43a047"],standard:"Abstrakcia, rytmus, farba, zážitok."}
];
export const lessons=rawLessons.map(l=>({...l,mainImage:svgData(l.title,l.colors),thumbs:Array.from({length:6}).map((_,i)=>svgData(`${l.title} ${i+1}`,i%2?[...l.colors].reverse():l.colors))}));
export function normalize(s){return String(s||"").toLowerCase().replace(/[áä]/g,"a").replace(/č/g,"c").replace(/ď/g,"d").replace(/é/g,"e").replace(/í/g,"i").replace(/[ľĺ]/g,"l").replace(/ň/g,"n").replace(/[óô]/g,"o").replace(/ŕ/g,"r").replace(/š/g,"s").replace(/ť/g,"t").replace(/ú/g,"u").replace(/ý/g,"y").replace(/ž/g,"z").replace(/[.,;]/g," ").replace(/\s+/g," ").trim();}
function scoreLesson(l,q){q=normalize(q);const text=normalize([l.title,l.grade,l.theme,l.technique,l.method,l.goal,l.duration,l.difficulty,l.tools.join(" "),l.procedure.join(" "),l.artists.map(a=>a.join(" ")).join(" ")].join(" "));const ignored=new Set(["rocnik","dnes","ucim","chcem","tema","technika","pre"]);const words=q.split(/\s+/).filter(w=>w.length>1&&!ignored.has(w));let s=0;for(const w of words) if(text.includes(w)) s+=3;["1","2","3","4","5"].forEach(n=>{if(q.includes(n)&&l.grade.includes(n+".")) s+=12});return s;}
export function searchLessons(query){return lessons.map(l=>({l,s:scoreLesson(l,query)})).sort((a,b)=>b.s-a.s).map(x=>x.l);}
